FROM carlomt/alghero-geant4

RUN apt-get update && \
    apt-get -yq install \    
    python3 \
    python3-pip \
    && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    rm -rf /var/cache/apt/archives/* && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install \
    numpy \
    matplotlib \
    pandas \
    ipython \
    jupyter \
    awkward \
    uproot