FROM carlomt/alghero-geant4

RUN apt-get update && \
    apt-get -yq --no-install-recommends install \    
    python3
    && \
    apt-get -y autoremove && \
    apt-get -y clean && \
    rm -rf /var/cache/apt/archives/* && \
    rm -rf /var/lib/apt/lists/*

RUN python -m pip install --upgrade pip && \
    pip install numpy matplotlib pandas ipython jupyter awkward uproot